export const U_LAYER_INDEX = 0;
export const L_LAYER_INDEX = 1;
export const F_LAYER_INDEX = 2;
export const R_LAYER_INDEX = 3;
export const B_LAYER_INDEX = 4;
export const D_LAYER_INDEX = 5;
export const NUMBER_OF_FACES = 6;
export const STICKERS_ON_FACE = 9; // nice!
export const NUMBER_OF_STICKERS_ON_CUBE = NUMBER_OF_FACES * STICKERS_ON_FACE;